  POST http://localhost:3003/api/users/
Content-Type: application/json
  
    {
      "username": "user6",
      "name": "Superuser",
      "password": "salainen",
      "blogs": [ 
          {
          "id": "62851601e4b59116fa7c3c7a"
          },
           {
          "id": "628516275eddd141d56b2e06"
          }
      ]
    }